apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-models-pvc
  namespace: vllm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: ${nfs_size_gb}Gi
  selector:
    matchLabels:
      pv-name: vllm-models-pv
