name: deepsix Cleanup
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  cleanup:
    name: Clean up DigitalOcean resources
    runs-on: ubuntu-latest
    container:
      image: registry.digitalocean.com/scale-with-simplicity-test/terraform-test:latest
      credentials:
        username: solutions@digitalocean.com
        password: ${{ secrets.TEST_DIGITALOCEAN_ACCESS_TOKEN }}
    env:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.TEST_DIGITALOCEAN_ACCESS_TOKEN }}
      SPACES_ACCESS_KEY_ID: ${{ secrets.TEST_SPACES_ACCESS_KEY_ID }}
      SPACES_SECRET_ACCESS_KEY: ${{ secrets.TEST_SPACES_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run deepsix cleanup
        run: deepsix --all --force
