name: nat-gateway PR Check
on:
  pull_request:
    paths:
      - 'reference-architectures/nat-gateway/**/*.tf'
      - 'reference-architectures/nat-gateway/test/**/*'
      - '.github/workflows/nat-gateway-pr-check.yaml'
      - '.github/workflows/workflow-terraform-pr-check.yaml'

jobs:
  call-common:
    uses: ./.github/workflows/workflow-terraform-pr-check.yaml
    with:
      module_path: reference-architectures/nat-gateway
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.TEST_DIGITALOCEAN_ACCESS_TOKEN }}
